apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOmFkbWluQHBvc3RncmVzLWRiLXNlcnZpY2U6NTQzMi93aGl0ZWJvYXJk
  JWT_SECRET: wpY5Y2QxYWNlMDBiOWQ3Mjc1MDEzNTFjMTE1NjE3ZGRhYmM3MTk4ZGVmYTJmYjk0ODA0ZjcyYzExMDA2MTk5OTg2
  REFRESH_SECRET: wpZiOTRlOTQyNmRkMWU1YWUxOGRkOTAzNzBhNzlhMjNiYTQ1YWFjNDI3MGNlNDcwNGEzYTZlNTdkYzM3MTVlM2Jl